services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    volumes:
      - vue_dist:/app/dist-volume

  backend:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    build:
      context: ./backend
    environment:
      - WEBAUTHN_RPID=${WEBAUTHN_RPID}
      - WEBAUTHN_RP_ORIGIN=${WEBAUTHN_RP_ORIGIN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PYTHON_OCR_URL=http://ocr:8081/ocr
      - RCLONE_REMOTE=b2crypt:FileLogix
      - RCLONE_CONFIG=/config/rclone/rclone.conf
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - /srv/FileLogix/files:/srv/FileLogix/files
      - /srv/FileLogix/backups:/srv/FileLogix/backups
      - /home/owenrhoekstra/.config/rclone/rclone.conf:/config/rclone/rclone.conf:ro
    depends_on:
      frontend:
        condition: service_started
      redis:
        condition: service_started
      ocr:
        condition: service_healthy
      cloudflared:
        condition: service_started
    restart: unless-stopped


  caddy:
    image: caddy:2-alpine
    ports:
      - "3500:3500"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - vue_dist:/srv/www
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run filelogix
    volumes:
      - /home/owenrhoekstra/.cloudflared:/etc/cloudflared
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:6380:6379"

  ocr:
    build: ./ocr
    ports:
      - "127.0.0.1:8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   # AMQP protocol port (used by your Go/Python apps)
      - "15672:15672" # Web Management UI port (open http://localhost:15672 in your browser)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  vue_dist:
